encoder: efficientnet-b1
weights: imagenet
decoder: unet
lr: 8.317637711026709e-05
seed: 42
patience: 5
num_workers: 2
batch_size: 16
epochs: 31
classes: 2
loss: CE
optimizer: Adam
scheduler: cosine
gpu: True
LGJ: False
debug: False
all_data: False
ds_path: 'data'
selected_folds: 4
selected_bands: ['B02','B03','B04','B08']