encoder: segnet34
weights: imagenet
decoder: unet
lr: 8.317637711026709e-05
seed: 42
patience: 5
num_workers: 2
batch_size: 16
epochs: 31
classes: 2
loss: CE
activation: Adam
scheduler: cosine
gpu: True
train_transform: train_transform
val_transform: None
LGJ: False
debug: True
all_data: False
ds_path: 'data'
selected_folds: 4
selected_bands: ['B02','B03','B04','B08']